### ISSUE TITLE
Feature Request: see images in full screen on click

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/plugin-site#1245]
Currently when looking at plugin doc, the images can be too small to be readable, and when we click on them we are redirected to GitHub.
Example: https://plugins.jenkins.io/config-file-provider/

I'd like a modal (or similar) to be open on click instead, displaying the image filling the screen and dismissed with another click.

**Comment by lzeee** [comment]
Hi,  @lemeurherve 

I'm Gong. I‘m preparing to apply for GSoC 2023: [Displaying of Plugin Health Scores](https://www.jenkins.io/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores/) and trying to understand this project.

I tried to solve this issue in this PR: https://github.com/jenkins-infra/plugin-site/pull/1311

**Comment by sridamul** [comment]
Will the documentation render in the local env? 
![Screenshot 2024-01-25 193953](https://github.com/jenkins-infra/plugin-site/assets/107404972/fa20aa7f-3155-46e0-bf62-0239a8b5d828)


If so can anyone help me to render the page locally?

**Comment by sridamul** [comment]
@krisstern Can you help me with finding out why the documentation page is not rendered locally?

![Screenshot 2024-01-25 193953](https://github.com/jenkins-infra/plugin-site/assets/107404972/ed809692-1573-4e1b-9be3-158b9b28f639)

**Comment by krisstern** [comment]
Hi @sridamul, 
I think maybe @halkeye would know more about it and be able to explain the reason why, but from what I recall the plugin docs are supposed to render like this locally.

**Comment by sridamul** [comment]
> I think maybe @halkeye would know more about it

Thank you! @krisstern

> but from what I recall the plugin docs are supposed to render like this locally.

#1311 In this PR, @lzeee had rendered the [page](https://user-images.githubusercontent.com/21041025/224523901-f3a85ad8-ef0e-40cf-a94a-10c5ba853069.gif) locally.

**Comment by krisstern** [comment]
Might have to do with this https://github.com/jenkins-infra/plugin-site/pull/1311#issuecomment-1465120929. That's why @lzeee could render everything on the page, but that may not be a recommended way.

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/plugin-site/blob/2cb4b668c3e8c9bd0f160abbd406a9e9200e6809/CONTRIBUTING.md?plain=1#L76

It should get updated to mention [GET_CONTENT_SINGLE](https://github.com/jenkins-infra/plugin-site/blob/2cb4b668c3e8c9bd0f160abbd406a9e9200e6809/plugins/gatsby-source-jenkinsplugins/utils.mjs#L49) which is way faster/easier to develop with rather than pulling down the

**Comment by lzeee** [comment]
Hi, these should be clearly described in the CONTRIBUTING document of the
corresponding project.

I think it might be that the local environment needs to be set up and the
corresponding data can be displayed on the web page after being pulled
locally.

Due to some reasons, I did not complete the relevant PR at that time, so my
understanding of the project was very limited. Hope you have fun in the
open source community.

Sridhar S ***@***.***> 于2024年1月27日周六 17:29写道：
