### ISSUE TITLE
#enhancment: changing the component style

### ISSUE THREAD

**Issue by Mahmoudgalalz** [jenkins-infra/plugin-site#1324]
![image](https://user-images.githubusercontent.com/42272376/230524923-55765f44-1ed9-4cd2-a61f-c9000eee87b2.png)

this is not clear, and it's returning too many plugins 

I recommend changing the layout to hold 4 cards and be centered when the side tab disappears

and changing the style to a bigger 

similar to this but adding a good style to it
![image](https://user-images.githubusercontent.com/42272376/230525454-47559380-f95c-4d01-a3b4-c6bdb7dcf200.png)
I will send a pr if this considered with my suggested UI

**Comment by Mahmoudgalalz** [comment]
also considering to put the pagination in the bottom

**Comment by MarkEWaite** [comment]
I prefer the current dense layout because it lets me see many plugins without scrolling.  When I'm seeking a plugin that matches a specific word (like GitHub or Bitbucket or Gitea) there are usually multiple matches that I need to consider.  The less dense layout that you're proposing will make less information fit on the screen for me.

**Comment by Mahmoudgalalz** [comment]
@MarkEWaite what about pagination at the bottom, and making them centered? after collapsing the side nav

**Comment by MarkEWaite** [comment]
I'll need to experiment with my Chromebook with its narrow vertical space before I offer an opinion on pagination at top or bottom.  I easily forget the experience navigating on a screen with limited vertical space when working at my desktop.

**Comment by Mahmoudgalalz** [comment]
okay, also I have seen a new update on blog pagination
![Screenshot 2023-04-07 at 5 05 33 AM](https://user-images.githubusercontent.com/42272376/230532864-18ee8779-9927-4c33-b96f-33315c5058fa.png)
we can do that there, and we can consider putting it in the Jenkins-components as it used on both sites

**Comment by krisstern** [comment]
I see the issue has been closed. But since @halkeye asked for feedback here is what I have found: 

Actually I prefer the current layout. It seems like the number of cards returned is responsive. So for my 13 inch laptop I see this: 

<img width="1440" alt="Screenshot 2023-04-07 at 12 25 48 PM" src="https://user-images.githubusercontent.com/88480540/230540910-102c5270-c359-4fdd-af4b-c8a723535b0c.png">

Maybe the only improvement I see is actually needed is to optimise also for the 13 inch version to display 5 cards per row instead of 4. I think that can be easily done with a change of either padding/margin settings.

**Comment by Mahmoudgalalz** [comment]
Yeah @krisstern, we can work on centering it and making enough cards per page, for each aspect ratio


![image](https://user-images.githubusercontent.com/42272376/230543833-cf22b5fe-eb15-458a-b01e-2c15ab3f5ebf.png)
I'm using a large screen that's why it has 8 per row, and this is good following 

but I recommend being centered this will be good as there's an empty alignment on the right when the sidebar is closed
so I can work on this
and empty alignment on the left 
![image](https://user-images.githubusercontent.com/42272376/230544081-d4915f94-5e94-4050-9930-b22b2b46cd51.png)

**Comment by krisstern** [comment]
I think some components like the pagination is already centered. Maybe we can try experimenting with centering the group of cards returned per search as well to give a more consistent look and feel.

**Comment by Mahmoudgalalz** [comment]
hi @halkeye I looked at the blogs pagination it has been changed there
so can the pagination be a component and used in the plugin site and blog site
I have an implementation in my head, but I'm asking if it would be good to do, or just change it to the in the plugin site as the blog site

**Comment by Mahmoudgalalz** [comment]
> I think some component like the pagination is already centered. Maybe we can try experimenting with centering the group of cards returned per search as well to give a more consistent look and feel.

awesome I will work on it and send a PR now

**Comment by krisstern** [comment]
Sounds good

**Comment by Mahmoudgalalz** [comment]
#1326 closed this issue
