### ISSUE TITLE
Issue with become checkfield in jenkins

### ISSUE THREAD

**Issue by kevinjobst** [jenkins-infra/plugin-site#633]
Problem with the Ansible jenkins Plugin

If you check the "become" option in the ansible jenkins plugin, and save it, jenkins does not keep this setting checked when you save it for a second time. This also applies for changes made the job config file, in the jenkins jobs folder.

## Screenshots 
Inital state:
![image](https://user-images.githubusercontent.com/82390883/114406776-18ee1800-9ba8-11eb-98be-578a6f172fb6.png)

Checking "become" and saving the configuration:
![image](https://user-images.githubusercontent.com/82390883/114406986-433fd580-9ba8-11eb-81dc-7d739c1099f9.png)

Reediting the jobs configuration (become is unchecked):
![image](https://user-images.githubusercontent.com/82390883/114407162-6bc7cf80-9ba8-11eb-91c1-287809ab1b5b.png)

and in the config file "become" is also false even if "become" is checked in the jobs menu configuration:
![image](https://user-images.githubusercontent.com/82390883/114407574-ceb96680-9ba8-11eb-8c13-a356ff4c11f4.png)

## Possible Solution 
- N/A

Regards
Kevin

**Comment by MarkEWaite** [comment]
Thanks for the report @Kevin-Jobst .  Unfortunately, this issue tracker is used to track issues with the plugin site rather than with specific plugins.  I believe that you're describing a software issue rather than a plugin site issue.  Ansible plugin issues are tracked at https://issues.jenkins.io/.  Could you raise an issue there?
