### ISSUE TITLE
dbForge DevOps Automation for SQL Server page - Help to restore access to Account

### ISSUE THREAD

**Issue by JordanS22** [jenkins-infra/plugin-site#721]
Problem with the [dbForge DevOps Automation for SQL Server](https://plugins.jenkins.io/dbforge-devops-automation-for-sqlserver) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Sorry, I'm having difficulty logging into jenkins.io using my account. Please help me restore access.

**Comment by MarkEWaite** [comment]
@JordanS22 
The issue tracker for the jenkins.io plugins site is used to track issues with the site and its APIs.  Your request seems to be a request for help with your jenkins.io account.

Please use the [mailing lists](https://www.jenkins.io/mailing-lists/) and the [chat channels](https://www.jenkins.io/chat/) for general questions.

If your issue is specifically related to jenkins.io login to a site that requires Jenkins LDAP credentials (like https://issues.jenkins.io), please try resetting your passwod through https://beta.accounts.jenkins.io/ .  If that does not work, then send email to my gmail account as mark dot earl dot waite.  I'll ask some questions, confirm that you are the owner of the account, etc., and once that is complete, can reset your password.

**Comment by JordanS22** [comment]
Thanks for your reply. Attempts to reset the password were unsuccessful, I wrote you a gmail.
