### ISSUE TITLE
ThinBackup page - Broken documentation link

### ISSUE THREAD

**Issue by alexistrejo** [jenkins-infra/plugin-site#723]
Problem with the [ThinBackup](https://plugins.jenkins.io/thinBackup) page, [source file](https://github.com/jenkins-infra/plugin-site/tree/master/src/templates/plugin.jsx)

Not a problem with template but with thinBackup plugin page. The documentation tab includes the broken link (404 response)  https://github.com/jenkinsci/think-backup-plugin. 

The "Help us improve this page" link is also broken.

The GitHub link under Links sections is correct.

The wrong link should be replaced for https://github.com/jenkinsci/thin-backup-plugin

## Screenshots 

![thinbackup](https://user-images.githubusercontent.com/1879780/122835863-c5d6c680-d2b6-11eb-9d48-6191861a7d2d.PNG)

## Possible Solution 

The wrong link should be replaced for https://github.com/jenkinsci/thin-backup-plugin

**Comment by halkeye** [comment]
Your absolutely right. 

Okay I looked into it.

The url for the docs has been updated to point to the right place - https://github.com/jenkinsci/thin-backup-plugin/pull/27 which is awesome, its been broken for a while. Buuut, there hasn't been a release(https://github.com/jenkinsci/thin-backup-plugin/releases) since then, so the new metadata isn't published.

If the maintainer really doesn't want to do a release with things fixed, someone can submit a PR to https://github.com/jenkins-infra/update-center2/blob/master/resources/wiki-overrides.properties but the proper fix is to do a release with the new data.

> The "Help us improve this page" link is also broken.

Yea, sadly all those links come from the same location.

**Comment by MarkEWaite** [comment]
Thanks for checking @halkeye .  I also submitted a pull request https://github.com/jenkinsci/thin-backup-plugin/pull/29 to move the images into the GitHub repository and make some other minor corrections to the documentation, just in case the maintainer decides they would like to release a new version with a documentation update.

@tofuatjava or @alienllama would you be willing to consider that pull request and create a new release so that the ThinBackup plugin documentation would be visible directly from the https://plugins.jenkins.io/thinBackup/ page rather than requiring that the user click a link at https://plugins.jenkins.io/thinBackup/ to take them to the page?

**Comment by zbynek** [comment]
This requires a release of thin-backup-plugin by @tofuatjava , nothing can be done in this repository.
