### ISSUE TITLE
Mobile Usability issues detected on plugins.jenkins.io

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/plugin-site#844]
According to google, 3 issues came up. Readme probably needs to be adjusted, or possibly plugin site css needs to be tweaked.

- [ ] Clickable elements too close together
- [ ] Content wider than screen
- [ ] Text too small to read

**Comment by harshlancer** [comment]
I want to work on this issue, please permit me to. Thank you

**Comment by zbynek** [comment]
Previously reported/fixed pages: https://plugins.jenkins.io/copyartifact/ , plugins from #750 

No known issues as of Aug 2022, keeping this issue open as placeholder

**Comment by Anurag-Band** [comment]
Hey @zbynek, is this issue solved, if not I want to Contribute to this ?? or any other issue you Suggest...

**Comment by zbynek** [comment]
@Anurag-Band This issue is a placeholder for Google alerts about mobile usability. At the moment there are not any. But you're welcome to browse the plugin site with a mobile device and look for possile usability issues (images distorted after scaling, wide tables that require a lot of horizontal scrolling etc.) The documentation is pulled from respective repositories of the plugins, so the pull requests would then need creating in those repos.
